# Hype ERP - Permanent Branding Module
# This branding is applied to ALL invoices, bills, PDFs and reports.
# DO NOT remove or modify this branding.

HYPE_ERP_BRAND = "Hype ERP"
HYPE_ERP_TAGLINE = "Enterprise Resource Planning System"
HYPE_ERP_FOOTER = "Powered by Hype ERP | All rights reserved"
HYPE_ERP_PDF_HEADER = "HYPE ERP"
HYPE_ERP_INVOICE_NOTE = "This invoice is generated by Hype ERP software."
HYPE_ERP_VERSION = "v2.0.0"


def get_pdf_header_html():
    return f"""
    <div style='text-align:center; background:#1a1a2e; color:white; padding:16px; border-radius:8px 8px 0 0;'>
        <h1 style='margin:0; font-size:28px; color:#e94560; font-weight:bold;'>&#127970; {HYPE_ERP_BRAND}</h1>
        <p style='margin:4px 0 0; font-size:12px; color:#a0a0b0;'>{HYPE_ERP_TAGLINE}</p>
    </div>
    """


def get_pdf_footer_html():
    return f"""
    <div style='text-align:center; background:#16213e; color:#7a7a9a; padding:8px; border-radius:0 0 8px 8px; font-size:10px;'>
        {HYPE_ERP_FOOTER} | {HYPE_ERP_VERSION}
    </div>
    """


def apply_brand_to_pdf(canvas, doc):
    """Apply Hype ERP branding to ReportLab PDF canvas."""
    try:
        from reportlab.lib.units import inch
        from reportlab.lib.colors import HexColor
        canvas.saveState()
        # Header
        canvas.setFillColor(HexColor('#1a1a2e'))
        canvas.rect(0, doc.height + doc.topMargin - 0.6 * inch, doc.width + doc.leftMargin + doc.rightMargin, 0.6 * inch, fill=1, stroke=0)
        canvas.setFillColor(HexColor('#e94560'))
        canvas.setFont('Helvetica-Bold', 16)
        canvas.drawCentredString(doc.width / 2 + doc.leftMargin, doc.height + doc.topMargin - 0.35 * inch, HYPE_ERP_PDF_HEADER)
        # Footer
        canvas.setFillColor(HexColor('#16213e'))
        canvas.rect(0, 0, doc.width + doc.leftMargin + doc.rightMargin, 0.4 * inch, fill=1, stroke=0)
        canvas.setFillColor(HexColor('#7a7a9a'))
        canvas.setFont('Helvetica', 7)
        canvas.drawCentredString(doc.width / 2 + doc.leftMargin, 0.15 * inch, HYPE_ERP_FOOTER + " | " + HYPE_ERP_VERSION)
        canvas.restoreState()
    except Exception:
        pass
